#!/bin/bash
#
# Example panel for LemonBoy's bar
source ~/.config/panel/panel_config

num_mon=$(xrandr | grep connected | wc -l)

while read -r line ; do
	case $line in
        C*)
            # clock output
            clock="${line#?}"
            ;;
        D*)
            # date output
            date="${line#?}"
            ;;
        E*)
            # battery
            bat="${line#?}"
            ;;
        G*)
            # volume
            vol="${line#?}"
            ;;
        P*)
            # power button
            powe="%{A:sudo poweroff:}%{A3:sudo systemctl reboot:}${line#?} %{A}%{A}"
            ;;
        W*) 
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
					      # active monitor
					      if [ $num_mon -gt 1 ] ; then
					              wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG}  ${name}  %{B-}%{F-}  "
					      fi
					      ;;
					m*)
					      # inactive monitor
					      if [ $num_mon -gt 1 ] ; then
					              wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG}  ${name}  %{B-}%{F-}  "
					      fi
					      ;;
					O*)
					      # focused occupied desktop	
                                              wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u}  ${name}  %{-u}%{B-}%{F-}"
					      ;;
					F*)
					      # focused free desktop
					      wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u}  ${name}  %{-u}%{B-}%{F-}"
					      ;;
					U*)
					      # focused urgent desktop
					      wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u}  ${name}  %{-u}%{B-}%{F-}"
					      ;;
					o*)
					      # occupied desktop
					      wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}  ${name}  %{A}%{B-}%{F-}"
					      ;;
					f*)
					      # free desktop
					      wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}  ${name}  %{A}%{B-}%{F-}"
					      ;;
					u*)
					      # urgent desktop
					      wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}  ${name}  %{B-}%{F-}"
					      ;;
				esac
				shift
			done
			;;
	esac
    printf "%s\n" "%{B${COLOR_HIGHLIGHT}}%{l} ${powe}%{B${COLOR_BACKGROUND}} %{c}center %{r}${vol}${bat} %{B${COLOR_HIGHLIGHT}} ${date} ${clock} "
done
