#!/bin/bash

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=28
PANEL_FONT_FAMILY="CamingoCode:size=9"
#ICON_FONT2="typicons:size=11"
ICON_FONT="MaterialIcons:size=11"

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"


# Power button
echo -e 'P\uE8AC' > $PANEL_FIFO &

while true; do
    # Clock
    echo -e 'C\uE924' $(date +'%l:%M:%S %p')

    # Date
    echo -e 'D\uE916' $(date +'%A, %b %e')

    # Battery
    lvl=$(cat /sys/class/power_supply/BAT0/capacity)
    stat=$(cat /sys/class/power_supply/BAT0/status)
    if [ $stat == "Charging" ]
    then
        icon='\uE1A3'
    elif (($lvl > 20))
    then
        icon='\uE1A4'
    else
        icon='\uE19C'
    fi

    echo -e 'E' $icon $lvl'%'

    # Networking
    wired=$(ip route get 8.8.8.8 | grep -Po 'dev \K\w+' | grep -qFf - /proc/net/wireless)
    if $wired; then
        icon='\uE8C2'
        ssid=''
    else
        icon='\uE63E'
        ssid=$(iwgetid -r)
    fi
#    if ! $conn; then
 #       icon='\uE1DA'
  #  else
  #      icon='\uE250'
   # fi
    echo -e 'F' $icon $ssid

    # Volume
    vol=$(amixer get Master | grep % | sed -n 1p | awk -F '[' '{print $2}' | awk -F ']' '{print $1}' | sed s/%//) 
    if [ $vol = 0 ]; then
        icon='\uE04F'
    elif [ $vol -lt 33 ]; then
        icon='\uE04E'
    elif [ $vol -lt 66 ]; then
        icon='\uE04D'
    else
        icon='\uE050'
    fi

    echo -e 'G' $icon $vol'%'

    sleep 1s
done > "$PANEL_FIFO" &

source ~/.config/panel/panel_config

cat "$PANEL_FIFO" | ~/.config/panel/panel_functions | lemonbar\
    -g x$PANEL_HEIGHT\
    -B "$COLOR_BACKGROUND"\
    -F "$COLOR_FOREGROUND"\
    -f "$PANEL_FONT_FAMILY"\
    -f "$ICON_FONT" | bash &

wait

