#!/bin/bash

source ~/.config/lemonbar/config

# Power
power(){
	echo -e 'P%{A:xterm -fa "Source Code Pro" -T floatme -e ~/power.sh -fs 12:}  \uE8AC  %{A}' > "$PANEL_FIFO"
}

# Clock
clock(){
	echo -e 'C\uE916' $(date +'%A, %b %e') '\uE924' $(date +'%l:%M:%S %p') > "$PANEL_FIFO"
}

# Battery
battery(){
	lvl=$(cat /sys/class/power_supply/BAT0/capacity)
	stat=$(cat /sys/class/power_supply/BAT0/status)
	if [ $stat == "Charging" ]
	then
		icon='\uE1A3'
	elif (($lvl > 20))
	then
		icon='\uE1A4'
	else
		icon='\uE19C'
	fi

	echo -e 'E' $icon $lvl'%' > "$PANEL_FIFO"
}

# Networking
networking(){
	wired=$(ip route get 8.8.8.8 | grep -Po 'dev \K\w+' | grep -qFf - /proc/net/wireless)
	if $wired; then
		icon='\uE8C2'
		ssid=''
	else
		icon='\uE63E'
		ssid=$(iwgetid -r)
	fi
	echo -e 'F' $icon $ssid > "$PANEL_FIFO"
}


# Volume
volume(){
	vol=$(amixer get Master | grep % | sed -n 1p | awk -F '[' '{print $2}' | awk -F ']' '{print $1}' | sed s/%//) 
	if [ $vol = 0 ]; then
		icon='\uE04F'
	elif [ $vol -lt 33 ]; then
		icon='\uE04E'
	elif [ $vol -lt 66 ]; then
		icon='\uE04D'
	else
		icon='\uE050'
	fi

	echo -e 'G' $icon $vol'%' > "$PANEL_FIFO"
}

# Music
music(){
	song=$(mpc current)
	echo -e 'M\uE405' $song > "$PANEL_FIFO"
}

# Player
player(){
	status=$(mpc status | grep -E "(playing|paused)" -o)
	progress=$(mpc status | grep -E "(playing|paused)" | rev | cut -c 3- | rev | cut -d "(" -f 2)
	full=$((progress / 2))
	shade=$((50 - full))
	if [ $status == "playing" ]; then
		icon='\uE034'
	else
		icon='\uE037'
	fi
	echo -e "N%{A:mpc -q prev && ${UPDATE} player music:} \uE045%{A}%{A:mpc -q toggle && ${UPDATE} player:} " $icon " %{A}%{A:mpc -q next && ${UPDATE} player music:}\uE044 %{A} ▌"$(seq -s█ $full|tr -d '[:digit:]')$(seq -s▓ $shade|tr -d '[:digit:]')"▐" > "$PANEL_FIFO"
}

# Workspaces
workspace() {
	wslist=$(\
		wmctrl -d \
		| awk '/ / {print $2 $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20}' ORS=''\
		| sed -e 's/\s*  //g' \
		-e 's/\*[ 0-9A-Za-z]*[^ -~]*/\\uE3FA /g' \
		-e 's/\-[ 0-9A-Za-z]*[^ -~]*/%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update workspace:}\\uE836 %{A}/g' \
		-e 's/\*//g' \
		-e 's/ -/ /g' \
	)

	if (( $(wmctrl -d | wc -l) == 10)); then
		new=""
	else
		new=$(\
			wmctrl -d\
			| rev\
			| cut -c 1\
			| awk -v RS='\\s+' '{ a[$1] } END { for(i = 1; i in a; ++i); print i }'\
		)
		new="%{A:i3-msg -q workspace $new && ${UPDATE} workspace:}\uE3BA%{A}"
	fi

	echo -e "A$wslist$new" > "$PANEL_FIFO"
}