#!/bin/bash

source ~/.config/lemonbar/config

while read -r line ; do
	case $line in
		A*)
			# Workspace
			orkspace="${line#?}"
			;;
		C*)
			# clock output
			clock=" ${line#?} "
			;;
		E*)
			# battery
			bat="${line#?} "
			;;
		F*)
			# Networking
			net="${line#?} "
			;;
		G*)
			# volume
			vol="${line#?}"
			;;
		P*)
			# power button
			powe="${line#?}"
			;;
		M*)
			# Music
			mus="${line#?}"
			;;
		N*)
			# Player
			play="${line#?}"
			;;
		
	esac
	printf "%s\n" "%{B${COLOR_HIGHLIGHT}}%{F#ffffff}${powe}%{F-}%{B-}${play}%{c}${mus}${workspace}%{r}${vol}${bat}${net}%{B${COLOR_HIGHLIGHT}}%{F#ffffff}${clock}%{B-}%{F-}"
	sleep .1s
done | lemonbar\
	-g x$PANEL_HEIGHT\
	-B "$COLOR_BACKGROUND"\
	-F "$COLOR_FOREGROUND"\
	-f "$PANEL_FONT_FAMILY"\
	-f "$ICON_FONT" | bash &

while read -r line ; do
	case $line in
		A*)
			# Workspaces
			workspace="${line#?}"
			;;
	esac
	printf "%s\n" "${workspace}"
	sleep 5s
done | lemonbar\
	-b\
	-g "x25"\
	-B "#1c1c1c"\
	-F "#999999"\
	-f "$PANEL_FONT_FAMILY"\
	-f "$ICON_FONT" | bash &